name: Deploy to EC2

on:
  push:
    branches: [ main ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create .env file
        run: |
          cat << EOF > .env
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          CHARGEBEE_SITE=${{ secrets.CHARGEBEE_SITE }}
          CHARGEBEE_API_KEY=${{ secrets.CHARGEBEE_API_KEY }}
          CHARGEBEE_STRIPE_GATEWAY_ID=${{ secrets.CHARGEBEE_STRIPE_GATEWAY_ID }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          NODE_ENV=production
          EOF

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*,.env"
          target: "/home/ubuntu/NBA_backend"
          strip_components: 1

      - name: Restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            pm2 restart nba-backend || pm2 start dist/index.js --name "nba-backend" 